# Site settings
title: Sebte| A simple  site to test little projets based on open data and build with jekyll and emerald template
description: "A minimal blog"
url: "http://sebte.github.io"
author:
  name: "Seb Te"
  email: "seb.te@laposte.net"
  url: "http://sebte.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
